require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/flagged_for_reviews", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # FlaggedForReview. As you add validations to FlaggedForReview, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FlaggedForReview.create! valid_attributes
      get flagged_for_reviews_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      flagged_for_review = FlaggedForReview.create! valid_attributes
      get flagged_for_review_url(flagged_for_review)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_flagged_for_review_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      flagged_for_review = FlaggedForReview.create! valid_attributes
      get edit_flagged_for_review_url(flagged_for_review)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FlaggedForReview" do
        expect {
          post flagged_for_reviews_url, params: { flagged_for_review: valid_attributes }
        }.to change(FlaggedForReview, :count).by(1)
      end

      it "redirects to the created flagged_for_review" do
        post flagged_for_reviews_url, params: { flagged_for_review: valid_attributes }
        expect(response).to redirect_to(flagged_for_review_url(FlaggedForReview.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FlaggedForReview" do
        expect {
          post flagged_for_reviews_url, params: { flagged_for_review: invalid_attributes }
        }.to change(FlaggedForReview, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post flagged_for_reviews_url, params: { flagged_for_review: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested flagged_for_review" do
        flagged_for_review = FlaggedForReview.create! valid_attributes
        patch flagged_for_review_url(flagged_for_review), params: { flagged_for_review: new_attributes }
        flagged_for_review.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the flagged_for_review" do
        flagged_for_review = FlaggedForReview.create! valid_attributes
        patch flagged_for_review_url(flagged_for_review), params: { flagged_for_review: new_attributes }
        flagged_for_review.reload
        expect(response).to redirect_to(flagged_for_review_url(flagged_for_review))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        flagged_for_review = FlaggedForReview.create! valid_attributes
        patch flagged_for_review_url(flagged_for_review), params: { flagged_for_review: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested flagged_for_review" do
      flagged_for_review = FlaggedForReview.create! valid_attributes
      expect {
        delete flagged_for_review_url(flagged_for_review)
      }.to change(FlaggedForReview, :count).by(-1)
    end

    it "redirects to the flagged_for_reviews list" do
      flagged_for_review = FlaggedForReview.create! valid_attributes
      delete flagged_for_review_url(flagged_for_review)
      expect(response).to redirect_to(flagged_for_reviews_url)
    end
  end
end
